{{- if .Values.elasticsearch.indexCleaner.install }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.jaeger.serviceName }}-index-cleaner
  labels:
    name: {{ .Values.jaeger.serviceName }}-index-cleaner
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-index-cleaner
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-index-cleaner-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.elasticsearch.indexCleaner.labels }}
      {{- toYaml .Values.elasticsearch.indexCleaner.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.elasticsearch.indexCleaner.annotations }}
  annotations:
    {{- toYaml .Values.elasticsearch.indexCleaner.annotations | nindent 4 }}
  {{- end }}
spec:
  concurrencyPolicy: {{ .Values.elasticsearch.indexCleaner.concurrencyPolicy }}
  schedule: {{ .Values.elasticsearch.indexCleaner.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.elasticsearch.indexCleaner.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.elasticsearch.indexCleaner.failedJobsHistoryLimit }}
  suspend: false
  jobTemplate:
    spec:
      {{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
      ttlSecondsAfterFinished: {{ .Values.elasticsearch.indexCleaner.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          {{- if .Values.elasticsearch.indexCleaner.annotations }}
          annotations:
            {{- toYaml .Values.elasticsearch.indexCleaner.annotations | nindent 12 }}
          {{- end }}
          labels:
            name: {{ .Values.jaeger.serviceName }}-index-cleaner
            app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-index-cleaner
            app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-index-cleaner-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
            app.kubernetes.io/component: jaeger
            {{- include "jaeger.commonLabels" . | nindent 12 }}
            {{- if .Values.elasticsearch.indexCleaner.labels }}
              {{- toYaml .Values.elasticsearch.indexCleaner.labels | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ .Values.jaeger.serviceName }}-index-cleaner
          securityContext:
            {{- include "elasticsearch.indexCleaner.securityContext" . }}
          {{- with .Values.elasticsearch.indexCleaner.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.indexCleaner.priorityClassName }}
          priorityClassName: {{ .Values.elasticsearch.indexCleaner.priorityClassName }}
          {{- end }}
          containers:
          - name: {{ .Values.elasticsearch.indexCleaner.name }}
            image: {{ template "indexCleaner.image" . }}
            imagePullPolicy: {{ .Values.elasticsearch.indexCleaner.imagePullPolicy }}
            args:
              - {{ .Values.elasticsearch.indexCleaner.numberOfDays | quote }}
              - {{ include "elasticsearch.url" .}}
            env:
              - name: ES_SERVER_URLS
                value: {{ include "elasticsearch.url" .}}
              - name: ES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ if .Values.elasticsearch.existingSecret }}{{ .Values.elasticsearch.existingSecret }}{{- else }}jaeger-elasticsearch{{- end }}
                    key: username
              - name: ES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ if .Values.elasticsearch.existingSecret }}{{ .Values.elasticsearch.existingSecret }}{{- else }}jaeger-elasticsearch{{- end }}
                    key: password
              {{- if .Values.elasticsearch.client.tls.enabled }}
              - name: ES_TLS_ENABLED
                value: {{ .Values.elasticsearch.client.tls.enabled | quote }}
                {{- if or .Values.elasticsearch.client.tls.existingSecret (or .Values.elasticsearch.client.tls.ca .Values.elasticsearch.client.tls.cert .Values.elasticsearch.client.tls.key) }}
              - name: ES_TLS_CA
                value: /es-tls/ca-cert.pem
              - name: ES_TLS_CERT
                value: /es-tls/client-cert.pem
              - name: ES_TLS_KEY
                value: /es-tls/client-key.pem
                {{- else if .Values.elasticsearch.client.tls.insecureSkipVerify }}
              - name: ES_TLS_SKIP_HOST_VERIFY
                value: {{ .Values.elasticsearch.client.tls.insecureSkipVerify | quote }}
                {{- end }}
              {{- end }}
              {{- if .Values.elasticsearch.indexCleaner.extraEnv }}
                {{- toYaml .Values.elasticsearch.indexCleaner.extraEnv | nindent 14 }}
              {{- end }}
            resources:
              {{- toYaml .Values.elasticsearch.indexCleaner.resources | nindent 14 }}
            securityContext:
              {{- include "elasticsearch.indexCleaner.containerSecurityContext" . }}
            volumeMounts:
            {{- include "jaeger.opensearchCertificateVolumeMounts" . | nindent 12 }}
            {{- range .Values.elasticsearch.indexCleaner.extraConfigmapMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
            {{- range .Values.elasticsearch.indexCleaner.extraSecretMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
          restartPolicy: OnFailure
          {{- if .Values.elasticsearch.indexCleaner.affinity }}
          affinity:
            {{- toYaml .Values.elasticsearch.indexCleaner.affinity | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.indexCleaner.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.elasticsearch.indexCleaner.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.indexCleaner.tolerations }}
          tolerations:
            {{- toYaml .Values.elasticsearch.indexCleaner.tolerations | nindent 12 }}
          {{- end }}
          volumes:
          {{- include "jaeger.opensearchCertificateVolumes" . | nindent 10 }}
          {{- range .Values.elasticsearch.indexCleaner.extraConfigmapMounts }}
            - name: {{ .name }}
              configMap:
                name: {{ .configMap }}
          {{- end }}
          {{- range .Values.elasticsearch.indexCleaner.extraSecretMounts }}
            - name: {{ .name }}
              secret:
                secretName: {{ .secretName }}
        {{- end }}
{{- end }}
