{{- if eq .Values.jaeger.storage.type "cassandra" }}
{{- if not .Values.cassandraSchemaJob.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-cassandra
  labels:
    name: jaeger-cassandra
    app.kubernetes.io/name: jaeger-cassandra
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.cassandraSchemaJob.labels }}
      {{- toYaml .Values.cassandraSchemaJob.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.cassandraSchemaJob.annotations }}
  annotations:
    {{- toYaml .Values.cassandraSchemaJob.annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ include "cassandraSchemaJob.userName" . | b64enc }}
  password: {{ include "cassandraSchemaJob.password" . | b64enc }}
{{- end }}
{{- end }}
