name: Test

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: false
            artifact-id:
                type: string
                default: ''
            component:
                default:  '[
                    {"name": "jaeger-integration-tests", "file": "integration-tests/Dockerfile", "context": "integration-tests"},
                    {"name": "jaeger-readiness-probe", "file": "readiness-probe/Dockerfile", "context": "readiness-probe"},
                    {"name": "jaeger-transfer", "file": "docker/Dockerfile", "context": "docker"}
                  ]'
                description: 'component'
                required: true

jobs:
    # test:
    #     runs-on: ubuntu-latest
    #     strategy:
    #         matrix:
    #             component: ${{fromJson(github.event.inputs.component)}}
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v4

    #         - name: Run tests
    #           run: echo "Running tests for ${{ github.event.inputs.component }}"

    #         - name: Conditions
    #           id: conditions
    #           run: |
    #             if [ -n "${{ inputs.artifact-id }}" ]; then
    #                 echo "image=ghcr.io/${{ github.repository_owner }}/${{ inputs.artifact-id }}" >> $GITHUB_OUTPUT
    #             else
    #                 echo "image=ghcr.io/${{ github.repository_owner }}/${{ matrix.component.name }}" >> $GITHUB_OUTPUT
    #             fi

    #         - name: debug
    #           run:  echo ${{ steps.conditions.outputs.image }}





    # tag:
    #     uses: netcracker/qubership-workflow-hub/.github/workflows/tag-creator.yml@main
    #     with:
    #       tag-name: ${{ github.event.inputs.version }}
    docker-build:
        # needs: [tag]
        uses: nookyo/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
        with:
            ref: ${{ inputs.version }}
            download-artifact: false
            dry-run: true
            component: ${{ inputs.component }}


